"""
Python script to encode a png image into base64 for use in forms
Can be used from the command line _generate_gui_logo.py {imagename}

Assumes file (if exists) is a valid png file
"""
import os
import os.path
import StringIO
import sys
from base64 import b64encode, b64decode
#Get image path from arguements
imageFileName = sys.argv[1]
#Indicate error if no image provided
if not imageFileName:
    print "Provide image file"
    sys.exit()
#Indicate error if file does not exist
if not os.path.isfile(imageFileName):
    print "File does not exist"
    sys.exit()
#Open png file
infile = open(imageFileName, 'rb');
binImage = infile.read()
infile.close()
#Encode file to base 64
base64Image = b64encode(binImage)
#Format output python script
outputString = """\"""
Script generated by _generate_gui_logo.py for use in POZI Connect GUI 
\"""
from StringIO import StringIO
from base64 import b64decode
imageBase64 = \"""%s\"""
imageBinary = b64decode(imageBase64)
imageStream = StringIO(imageBinary)
""" % base64Image
#Setup script path
outFileName = os.path.dirname(imageFileName)
outFileName = outFileName + r'\gui_logo_png.py'
#Save script to system
outfile = open(outFileName, 'w')
outfile.write(outputString)
outfile.close()
